version: "3.7"
services:
  app:
    build:
      args:
        user: kuoz
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ${APP_NAME_CONFIG}
    container_name: ${APP_NAME_CONFIG}-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - default_network

  db:
    image: mysql:5.7
    container_name: ${APP_NAME_CONFIG}-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - default_network

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME_CONFIG}-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - default_network

networks:
  default_network:
    driver: bridge